spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate

security:
  jwt:
    token:
      secret-key: expedia-secret-key
      expire-length: 3600000
